# Generated by Django 4.1.1 on 2022-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0002_projects_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
