# Generated by Django 6.0 on 2025-12-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(choices=[('Python', 'Python'), ('API', 'API'), ('Automation', 'Automation'), ('Modeling', 'Modeling')], max_length=30)),
                ('repository', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
