# Generated by Django 6.0 on 2025-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('podcast', 'Podcast'), ('article', 'Article'), ('whitepaper', 'Whitepaper'), ('video', 'Video'), ('book', 'Book')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-date_added', '-created_at'],
            },
        ),
    ]
