version: '3.9'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME:-django_mypage}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-postgres}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "./scripts/start.sh"
    volumes:
      - ..:/app
      - node_modules:/app/frontend/node_modules
    ports:
      - '8000:8000'
      - '3000:3000'
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME:-django_mypage}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASS:-postgres}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASS:-postgres}@db:5432/${POSTGRES_NAME:-django_mypage}
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  node_modules:
